= Fauna AsciiDoc user guide
:description: User guide

This document prescribes the Fauna conventions for using AsciiDoc to create documentation for the https://docs.fauna.com/fauna/current/[Fauna documentation site]. In general, vanilla https://asciidoctor.org/docs/[AsciiDoc] notation is valid for Fauna documentation. This guide defines additional practices that promote consistency, for doc maintenance and tools, and ensure conformance to the xref:./style_guide.md[Fauna Documentation Style Guide].

== Reference

https://asciidoctor.org/docs/[Asciidoctor Documentation]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

https://docs.antora.org/antora/latest/asciidoc/asciidoc/[Antora Docs - AsciiDoc]

== File naming

=== Topic filenames

Each file should cover a single topic and the topic should be evident from the filename, with an extension of `adoc`.

Generally, use snake case for filenames, where the filename is lowercase and multiple words in the name are separated by an underscore, such as `get_started_fsl.adoc`.

An exception is where the topic is a method or property. In that case, the filename should be the same as the method or property name. Fauna method names are camel case. For example, `lastIndexWhere.adoc`.

=== Example filenames

Currently, there is limited example file naming convention. An example filename might be descriptive of the example, include a number that indicates its relationship to other examples, or use some other logical naming scheme. All example files, regardless of naming convention, separate multiple words in the filename with a dash. For example, `instance-createData-1.fql`.

All example input files have the extension `.fql`. Corresponding example output files have the same base name followed by the extension `.fql.out`:

> **Input file:**
>
> instance-createData-1.fql
>
> **Output file:**
>
> instance-createData-1.fql.out

== Syntax

tbd

=== Paragraphs

tbd

- Simple
+
tbd

- Literal
+
tbd

- Syntax
+
tbd

line length

line break

=== Text formatting

tbd

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-formatting[Text formatting].

syntax highlighting: <<semantic-hilite>>

=== Links

tbd

==== Intrapage link

==== Interpage link

==== External link

=== Document header

tbd

metadata

=== Section titles

tbd

----
= Types

== Scalar types

=== String

==== Interpolated strings
----

There should never be a single subheading below a heading level.

See https://learn.microsoft.com/en-us/style-guide/scannable-content/headings[Microsoft Style Guide - Headings] for more guidance on how to construct a heading at each level.

=== Includes

tbd

=== Lists

tbd

==== Unordered

==== Ordered

==== Definition

=== Images

tbd

[[semantic-hilite]]
=== Keyboard, button, and other UI macros

tbd

----
Click the btn:[RUN QUERY] button.

Type kbd:[Control + C] to ...

On the uitext:Home[] page, click the database uitext:Name[].
----

yields:

> Click the **RUN QUERY** button.
>
> Type **Control + C** to ...
>
> On the **Home** page, click the database **Name**.

=== Literals and source code

tbd

=== Admonitions

tbd

=== Code blocks

tbd

=== Example blocks

tbd

=== Tables

tbd

See https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-cell/[Asciidoctor Docs - Align Content by Cell].

==== Simple

----
[%autowidth, cols="a,a", options="header"]
|===
| Property
| Description

| uitext:NAME[]
| Database name. Use the arrows to sort the list on database name.

| uitext:REGION-GROUP[]
| Database region group. Use the arrows to sort the list on region group.
|===
----

For fixed-width columns, omit `%autowidth` and replace the `a` in `cols=` with relative column width values.:

----
[cols="8,45,~", options="header"]
|===
| Operator
| Syntax
| Description

| `+`
| _operand1_ `+` _operand2_
| Addition, sums the operands.
|===
----

Omit the table header row by omitting `options="header"`:

----
[%autowidth,cols="a,a,a"]
|===
| `abort`
| `constraint_failure`
| `constraint_violation`

| `contended_transaction`
| `divide_by_zero`
| `document_already_exists`

| `document_not_found`
| `forbidden`
| `index_out_of_bounds`
|===
----

==== Nested

tbd

----
[%autowidth,cols="a,a,a", options="header"]
|===
| Field name
| Value type
| Description

| `id`
| type:long[]
| A unique identifier for a document. {server} assigns this value at creation.

| `document`
| ref
| Document associated with this credential. This object has these fields.

[%autowidth,cols="a,a"]
!===
! `id`
! Document identifier associated with this credential.

! `coll`
! Name of `type:Collection[]` that stores this document.
!===
|===
----

=== Comments

tbd

----
////
*Comment* block

Use: hide comments
////
----

=== Attributes and substitutions

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#attributes-and-substitutions[Attributes and substitutions].

=== Text replacements

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[Text replacements].

== Extensions

tbd
