= Fauna AsciiDoc user guide
:description: User guide

This document prescribes the Fauna conventions for using AsciiDoc to create documentation for the https://docs.fauna.com/fauna/current/[Fauna documentation site]. In general, vanilla https://asciidoctor.org/docs/[AsciiDoc] syntax applies to Fauna documentation. This guide defines additional practices that promote consistency, for doc maintenance and tools, and ensure conformance to the xref:./style_guide.md[Fauna Documentation Style Guide].

Many but not all of the guidelines listed in this document are checked at build time when running `make`, `make quick`, or `make checks`. To publish the documentation, the build should have no errors.

== Reference

https://asciidoctor.org/docs/[Asciidoctor Documentation]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

https://docs.antora.org/antora/latest/asciidoc/asciidoc/[Antora Docs - AsciiDoc]

== File naming

=== Topic filenames

Each file should cover a single topic and the topic should be evident from the filename, with an extension of `adoc`.

Generally, use snake case for filenames, where the filename is lowercase and multiple words in the name are separated by an underscore, such as `get_started_fsl.adoc`.

An exception is where the topic is a method or property. In that case, the filename should be the same as the method or property name. Fauna method names are camel case. For example, `lastIndexWhere.adoc`.

=== Example filenames

Currently, there is limited example file naming convention. An example filename might be descriptive of the example, include a number that indicates its relationship to other examples or use some other logical naming scheme. All example files, regardless of naming convention, separate multiple words in the filename with a dash. For example, `instance-createData-1.fql`.

All example input files have the extension `.fql`. Corresponding example output files have the same base name followed by the extension `.fql.out`:

> **Input filename:**
>
> instance-createData-1.fql
>
> **Output filename:**
>
> instance-createData-1.fql.out

== Structure

=== Document header

This describes the standardized document front matter and optional attribute definitions.

----
= Dashboard quick start
:description: Dashboard Quick Start
:page-aliases: learn:quick_start/quick_start.adoc
----

The first line of every document is a level 0 heading (`=`), which is the title of the document:

----
= Dashboard quick start
----

This is the title that should be displayed in the left-side nav panel. Refrain from changing the title in the `nav.adoc` file.

The level 0 heading is immediately followed by _description_ metadata:

----
:description: Dashboard Quick Start
----

The `:description:` attribute supports SEO and should be descriptive of the topic. It generates the HTML description metadata tag:

----
<meta name="description" content="Dashboard Quick Start">
----

The following optional Antora and locally defined attributes provide control over page presentation.

[cols="2,1"]
|===
| Attribute | Description and usage

| `:page-aliases:`
| If the page was moved, use this to redirect the previous URL to this page. For example, if the page was previously in the quick_start directory of the learn module, the following redirects that URL to this page: `page-aliases: learn:quick_start/quick_start.adoc`.

| `:page-language-bar:`
| For documents that use the `example::` extension to select among examples, such as different programming languages, `:page-language-bar:` must be set to `true`. The default value is `false`.

| `:page-layout:`
| Setting `page-layout` to `home` makes styling features available that are defined for the home page style.

Example:

    = Welcome to Fauna docs +
    :description: Welcome to Fauna docs +
    :page-layout: home

| `:hide-from-nav:`
| To keep documents from appearing in the left nav panel, set `:hide-from-nav:` to `true`.
|===

=== Section titles

This describes the notation for section titles and the number of levels permitted.

----
= Types
:description: FQLX types

This section lists the ...

== Scalar types

The scalar types are ...

=== String

String literals are ...

==== Interpolated strings

Double-quoted strings support the ...
----

After the level 0 document title, the example shows level 1 through level 3 headings. Documents should not exceed a depth of level 3 (`====`), and a single, hanging sublevel should never exist by itself. An exception to the number of levels restriction is when documenting a naturally hierarchical topic, such as a REST HTTP reference, in which case levels can extend to match the hierarchy.

See https://learn.microsoft.com/en-us/style-guide/scannable-content/headings[Microsoft Style Guide - Headings] for guidance on how to construct a heading at each level.

=== Includes

Use the `include::` directive to include text from another file.

----
include::partial$table-shell-common-options-2.adoc[]
----

This is typically used to share reusable content.

Included files within a section are located in the /module/<section>/partials directory. Globally included files are located in the /modules/&#95;includes/partials directory.

=== Line length

Line length is limited to 80 characters.

=== Forced line break

To force a line break in a simple paragraph, literal block, or a paragraph included in a table, add `<space>+` at the end of the line where you want the break:

----
Supported Python versions: +
Python 3.9 +
Python 3.10 +
Python 3.11
----

Which is rendered as:

Supported Python versions: +
Python 3.9 +
Python 3.10 +
Python 3.11

== Syntax

tbd

=== Paragraphs and blocks

tbd

==== Simple paragraph

Construct a paragraph as continuous text, terminated by an empty line. Line feeds within the 80-character limited line length are not displayed. An empty line separates paragraphs.

----
The previous Collection tutorial uses built-in Set methods
that traverse the whole dataset to get the data you want.

This tutorial shows you how to use indexes as a more
cost-effective and performant alternative.
----

Which is rendered as:

----
The previous Collection tutorial uses built-in Set methods that traverse the whole dataset to get the data you want.

This tutorial shows you how to use indexes as a more cost-effective and performant alternative.
----

[[literal-block]]
==== Literal block

A literal block that displays content as entered uses the AsciiDoc listing/source delimiter (`----`):

    -----
    const type = "book"
    let query  = fql`Product.where(.type == ${type})`
    let result = await client.query(query)
    console.log(result)
    -----

Alternatively, you can indent the lines four spaces:

> &nbsp;&nbsp;&nbsp;&nbsp;const type = "book" +
> &nbsp;&nbsp;&nbsp;&nbsp;let query  = fql`Product.where(.type == ${type})` +
> &nbsp;&nbsp;&nbsp;&nbsp;let result = await client.query(query) +
> &nbsp;&nbsp;&nbsp;&nbsp;console.log(result)

Both methods render the following literal block:

    const type = "book"
    let query  = fql`Product.where(.type == ${type})`
    let result = await client.query(query)
    console.log(result)

==== Admonitions

Fauna documentation is limited to including the following admonitions, in order of severity, with the given syntax:

[cols="2,1"]
|===
| Admonition | Usage

| `[TIP]`
| Use the _tip_ admonition to provide additional but non-essential information, such as a best practice.

| `[NOTE]`
| Use the _note_ admonition sparingly. Technical writers and developers tend to over use this admonition in an effort to highlight content. In general, use the _important_ and _warning_ admonitions to bring attention to content. Otherwise, consider all content to be equally important or it wouldn't be in the document.

| `[IMPORTANT]`
| Use the _important_ admonition if it's absolutely necessary to bring attention to the content. Its use should be minimal.

| `[WARNING]`
| Use the _warning_ admonition to caution the reader against a corrupting or catestropic action that might have significant implact if not heeded. A warning generally means "Do not do this".
|===

Admonition blocks are delimited by the example delimiter (`====`) and can include multiple paragraphs:

----
[TIP]
=====
Two indexes with the same shape, except for the `id` field specified
last and ascending, are treated as the same shape. Effectively, including
`id` as the last covered value is the same as not including it.
=====
----

Which is rendered as the following, with the admonition name replaced by the associated Fauna admonition icon:

[TIP]
=====
Two indexes with the same shape, except for the `id` field specified
last and ascending, are treated as the same shape. Effectively, including
`id` as the last covered value is the same as not including it.
=====

==== Code blocks

A code block can be simply written as a <<literal-block>>. For language-specific syntax highlighting, precede the literal block with the `[source, <language>]` macro:

    [source, json]
    ----
    {
        "error": {
            "code": "invalid_function_invocation",
            "message": "The function `al` doesn't exist on `Collection`"
        }
    }
    ----

Which is rendered as:

[source, json]
----
{
    "error": {
        "code": "invalid_function_invocation",
        "message": "The function `al` doesn't exist on `Collection`"
    }
}
----

The literals for commonly supported languages are:

[cols="1,1,1,1,1"]
|===

| bash
| csharp
| fqlx
| go
| graphql

| html
| HTTP
| ini
| java
| javascript

| json
| powershell
| python
| scala
| shell

| sql
| text
| xml
| yaml
|
|===

==== Example blocks

The examples block is used to display code examples for the supported programming languages. Example blocks are used with the `selector:langs[]` directive to select a programming language using the language selector tab.

Include code examples for the languages you want to show in the /attachments directory.

General syntax:

----
example::<location>/<exampleFile>[OPTIONS]
----

The `<location>` is the path of the example file in the /attachments directory.

The `<exampleFile>` is the name of the example code file in `<location>`. All programming language example source files must have the same `<exampleFile>` name, differing only by the file name extension for the language, such as .go, java, and .javascript. Also, each example must have a corresponding example output file of the same name followed by the .out extension. For example, the driver_quick_start.js file has a corresponding driver_quick_start.js.out file.

OPTIONS:

You can declare multiple options in the `example::` directive.

[cols="2,1"]
|===
| Option | Description

| `full`
| Enable examples for all provided programming languages: +
`true` = Enable all provided languages.+
`false` = Enable only those languages specified by the `only` option.
| `only`
| Enable a specific programming language example with a matching programming language file extension, such as `only=js` to display only the JavaScript example.

| `noout`
| Disable the example output display: +
`true` = Disable displaying the example's corresponding .out file.
`false` = (default) Display the example's corresponding .out file.

| `onlyout`
| Disable the example input display: +
`true` = Disable the example's input file.
`false` = (default) Display the example's input file.
|===

==== Syntax block

By convention, a Fauna documentation syntax block is delimited using the AsciiDoc example delimiter (`====`):

----
====
Date(dateString: String): Date
====
----

==== Comment block

To include a comment in the document without rendering the comment in the presentation, include the comment in a comment delimiter (`////`):

----
////
*Comment* block

Use: hide comments
////
----

=== Text formatting

Inline text formatting can be done using AsciiDoc notation. See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-formatting[Text formatting].

However, where semantic highlighting macros exist, they should be preferred over the raw AsciiDoc notation. See <<semantic-hilite>>.

Follow the xref:./style_guide.md[Fauna Documentation Style Guide] for the judicious use of text formatting.

Semantic highlighting is much preferred over using such symbols as quotation marks (`"..."`) for emphasis and parentheses (`(...)`) for appositives, a common technical documentation creator practice.

=== Links

==== Intrapage link

==== Interpage link

==== External link

=== Lists

==== Unordered

==== Ordered

==== Definition

=== Tables

Table notation supports standard AsciiDoc table notation plus internal macros.

See the following AsciiDoc table documentation for common table formatting options that are used to render tables in Fauna documentation:

- https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-cell/[Align Content by Cell]
- https://docs.asciidoctor.org/asciidoc/latest/tables/format-cell-content/[Format Content by Cell]
- https://docs.asciidoctor.org/asciidoc/latest/tables/span-cells/[Span Columns and Rows]

==== Simple table

----
[%autowidth, cols="a,a", options="header"]
|===
| Property
| Description

| uitext:NAME[]
| Database name. Use the arrows to sort the list on database name.

| uitext:REGION-GROUP[]
| Database region group. Use the arrows to sort the list on region group.
|===
----

Which is rendered as:

[cols="2,1"]
|===
| Property | Description

| **NAME[]**
| Database name. Use the arrows to sort the list on database name.

| **REGION-GROUP[]**
| Database region group. Use the arrows to sort the list on region group.
|===


For fixed-width columns, omit `%autowidth` and replace the `a` in `cols=` with relative column width values.:

----
[cols="8,45,~", options="header"]
|===
| Operator
| Syntax
| Description

| `+`
| _operand1_ `+` _operand2_
| Addition, sums the operands.
|===
----

Omit the table header row by omitting `options="header"`:

----
[%autowidth,cols="a,a,a"]
|===
| `abort`
| `constraint_failure`
| `constraint_violation`

| `contended_transaction`
| `divide_by_zero`
| `document_already_exists`

| `document_not_found`
| `forbidden`
| `index_out_of_bounds`
|===
----

==== Nested table

Use the exclamation mark (`!`) to nest a table within a table cell:

----
[%autowidth,cols="a,a,a", options="header"]
|===
| Field name
| Value type
| Description

| `id`
| type:long[]
| A unique identifier for a document. {server} assigns this value at creation.

| `document`
| ref
| Document associated with this credential. This object has these fields.

[%autowidth,cols="a,a"]
!===
! `id`
! Document identifier associated with this credential.

! `coll`
! Name of `type:Collection[]` that stores this document.
!===
|===
----

All other table formatting notation continues to apply to a nested table.

=== Images

tbd

[[semantic-hilite]]
=== Keyboard, button, and other UI macros

tbd

----
Click the btn:[RUN QUERY] button.

Type kbd:[Control + C] to ...

On the uitext:Home[] page, click the database uitext:Name[].
----

yields:

> Click the **RUN QUERY** button.
>
> Type **Control + C** to ...
>
> On the **Home** page, click the database **Name**.

=== Attributes and substitutions

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#attributes-and-substitutions[Attributes and substitutions].

=== Text replacements

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[Text replacements].

== Fauna extensions

tbd
