= Fauna AsciiDoc user guide
:description: User guide

This document shows the prescribed Fauna conventions for using AsciiDoc to create documentation that conforms to the xref:./style_guide.md[Fauna Documentation Style Guide].

== Reference

https://asciidoctor.org/docs/[Asciidoctor Documentation]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

https://docs.antora.org/antora/latest/asciidoc/asciidoc/[Antora Docs - AsciiDoc]

== File naming

tbd

== Syntax

tbd

=== Paragraphs

tbd

- Simple
+
tbd

- Literal
+
tbd

- Syntax
+
tbd

line length

newline

=== Text formatting

tbd

syntax highlighting

=== Links

tbd

==== Intrapage link

==== Interpage link

==== External link

=== Document header

tbd

metadata

=== Section titles

tbd

----
= Types

== Scalar types

=== String

==== Interpolated strings
----

See https://learn.microsoft.com/en-us/style-guide/scannable-content/headings[Microsoft Style Guide - Headings] for more guidance on how to construct a heading at each level.

=== Includes

tbd

=== Lists

tbd

==== Unordered

==== Ordered

==== Definition

=== Images

tbd

=== Keyboard, button, and other UI macros

tbd

----
Click the btn:[RUN QUERY] button.

Type kbd:[Control + C] to ...

On the uitext:Home[] page, click the database uitext:Name[].
----

yields:

Click the **RUN QUERY** button.

Type **Control + C** to ...

On the **Home** page, click the database **Name**.

=== Literals and source code

tbd

=== Admonitions

tbd

=== Code blocks

tbd

=== Example blocks

tbd

=== Tables

tbd

See https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-cell/[Asciidoctor Docs - Align Content by Cell].

==== Simple

----
[%autowidth, cols="a,a", options="header"]
|===
| Property
| Description

| uitext:NAME[]
| Database name. Use the arrows to sort the list on database name.

| uitext:REGION-GROUP[]
| Database region group. Use the arrows to sort the list on region group.
|===
----

For fixed-width columns, omit `%autowidth` and replace the `a` in `cols=` with relative column width values.

Omit the table header row by omitting `options="header"`:

----
[%autowidth,cols="a,a,a"]
|===
| `abort`
| `constraint_failure`
| `constraint_violation`

| `contended_transaction`
| `divide_by_zero`
| `document_already_exists`

| `document_not_found`
| `forbidden`
| `index_out_of_bounds`
|===
----

==== Nested

tbd

----
[%autowidth,cols="a,a,a", options="header"]
|===
| Field name
| Value type
| Description

| `id`
| type:long[]
| A unique identifier for a document. {server} assigns this value at creation.

| `document`
| ref
| Document associated with this credential. This object has these fields.

[%autowidth,cols="a,a"]
!===
! `id`
! Document identifier associated with this credential.

! `coll`
! Name of `type:Collection[]` that stores this document.
!===
|===
----

=== Comments

tbd

----
////
*Comment* block

Use: hide comments
////
----

=== Attributes and substitutions

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#attributes-and-substitutions[Attributes and substitutions].

=== Text replacements

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[Text replacements].

== Extensions

tbd
