= Fauna AsciiDoc user guide
:description: User guide

This document shows the prescribed Fauna conventions for using AsciiDoc to create documentation that conforms to the xref:./style_guide.md[Fauna Documentation Style Guide].

== Reference

https://asciidoctor.org/docs/[Asciidoctor Documentation]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

https://docs.antora.org/antora/latest/asciidoc/asciidoc/[Antora Docs - AsciiDoc]

== File naming

tbd

== Syntax

tbd

=== Paragraphs

tbd

- Simple
+
tbd

- Literal
+
tbd

- Syntax
+
tbd

line length

newline

=== Text formatting

tbd

syntax highlighting

=== Links

tbd

==== Intrapage link

==== Interpage link

==== External link

=== Document header

tbd

metadata

=== Section titles

tbd

----
= Types

== Scalar types

=== String

==== Interpolated strings
----

See https://learn.microsoft.com/en-us/style-guide/scannable-content/headings[Microsoft Style Guide - Headings] for more guidance on how to construct a heading at each level.

=== Includes

tbd

=== Lists

tbd

==== Unordered

==== Ordered

==== Definition

=== Images

tbd

=== Keyboard, button, and menu macros

tbd

----
Click the btn:[RUN QUERY] button.

Type kbd:[Control + C] to ...

On the uitext:Home[] page, click the database uitext:Name[].
----

yields:

Click the **RUN QUERY** button.

Type **Control + C** to ...

On the **Home** page, click the database **Name**.

=== Literals and source code

tbd

=== Admonitions

tbd

=== Code blocks

tbd

=== Example blocks

tbd

=== Tables

tbd

==== Simple

==== Nested

=== Comments

tbd

----
////
*Comment* block

Use: hide comments
////
----

=== Attributes and substitutions

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#attributes-and-substitutions[Attributes and substitutions].

=== Text replacements

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[Text replacements].

== Extensions

tbd
