= User guide
:description: User guide

This document shows the prescribed Fauna conventions for using AsciiDoc to create documentation that conforms to the xref:./style_guide.md[Fauna Documentation Style Guide].

== Reference

https://asciidoctor.org/docs/[Asciidoctor Documentation]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

https://docs.antora.org/antora/latest/asciidoc/asciidoc/[Antora Docs - AsciiDoc]

== File naming

tbd

== Syntax

tbd

=== Paragraphs

tbd

line length

newline

=== Text formatting

tbd

syntax highlighting

=== Links

tbd

==== Intrapage

==== Interpage

==== External

=== Document header

tbd

metadata

=== Section titles

tbd

Level 0 heading (document title):

    = Types

Level 1 heading:

    == Scalar types

Level 2 heading:

    === String

Level 3 heading:

    ==== Interpolated strings

tbd

    Types

    Scalar types

    String

    Interpolated strings


=== Includes

tbd

=== Lists

tbd

==== Unordered

==== Ordered

==== Definition

=== Images

tbd

=== Keyboard, button, and menu macros

tbd

=== Literals and source code

tbd

=== Admonitions

tbd

=== Code blocks

tbd

=== Example blocks

tbd

=== Tables

tbd

==== Simple

==== Nested

=== Comments

tbd

=== Attributes and substitutions

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#attributes-and-substitutions[Attributes and substitutions].

=== Text replacements

See https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[Text replacements].

== Extensions

tbd
